### PR TITLE
Update storage queue from t1 to t2

### PR DESCRIPTION
**Pull request by v-xuto**
1.Update storage queue from t1 to t2
2.Update files:

- 1. README.md
- 2. config.py
- 3. queue_advanced_samples.py 
- 4. queue_basic_samples.py 
- 5. requirements.txt 
- 6. start.py 

@jongio for notification.

### CODE REVIEW

**Comment by v-xuto** [comment]
@ lmazuel - Can you help review this PR?

**Review by tasherif-msft — APPROVED** [review]

**Review by lmazuel — APPROVED** [review]

**Comment by v-xuto** [comment]
@lmazuel  Could you help us merge this PR?

**Comment by lmazuel** [comment]
@tasherif-msft could you merge I don't have write access

**Comment by v-xuto** [comment]
@jameszliao-msft, @kyle-patterson , @tg-msft, @amishra-dev  Do you have permission for this repo? If so, please help merge this PR.

**Comment by v-xuto** [comment]
@jameszliao-msft, @kyle-patterson , @tg-msft, @amishra-dev Do you have permission for this repo? If so, please help merge this PR.

**Pull request merged**
